brew "fzf"
brew "ghq"
brew "git"
brew "git-delta"
brew "gnupg"
brew "go"
brew "node"
brew "pinentry-mac"
brew "python@3.9"
brew "ruby"
brew "starship"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

tap "homebrew/cask-fonts"
cask "font-fira-code"
cask "iterm2"
