#!/usr/bin/perl

$latex = 'uplatex -kanji=utf8 -file-line-error -interaction=nonstopmode';
$biber = 'biber -u -U --output_safechars';
$bibtex = 'upbibtex %O %B';
$dvipdf = 'dvipdfmx %O -o %D %S';
$makeindex = 'upmendex %O -o %D %S';
$max_repeat = 5;
$pdf_mode = 3;
$pdf_previewer = 'open -g';
