# prefix key
set -g prefix C-t
unbind C-b
bind C-a send-prefix

# scroll
set -g mouse on
bind-key -T edit-mode-vi WheelUpPane send-keys -X scroll-up
bind-key -T edit-mode-vi WheelDownPane send-keys -X scroll-down
set -s copy-command 'pbcopy'
