#!/bin/zsh

if ! git rev-parse >/dev/null 2>&1; then
  echo "Not a git repository" 1>&2
  return 1
fi

local cmd="command git worktree list 2>/dev/null"
local dir="$(eval "$cmd" | fzf-tmux +m --reverse | awk '{print $1}')"
if [[ -z "$dir" ]]; then
  return 1
fi

cd "$dir"
