#!/bin/zsh

local prefix="${CONDA_PREFIX:-${HOME}/.local/anaconda3}"
if [[ ! -d "$prefix" ]]; then
   echo "$prefix not found." >&2
   return 1
 fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$prefix/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$prefix/etc/profile.d/conda.sh" ]; then
        . "$prefix/etc/profile.d/conda.sh"
    else
        export PATH="$prefix/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

unset -f conda

conda "$@"
