#!/bin/zsh

local prefix=${CONDA_PREFIX:-/usr/local/anaconda3}

if [[ ! -d "$prefix" ]]; then
  echo "$prefix not found." >&2
  return 1
fi

unset -f conda
[[ -z "$CONDA_PREFIX" ]] && export CONDA_PREFIX="$prefix"
export PATH="$PATH:$CONDA_PREFIX/bin"

conda "$@"
