#!/usr/bin/env zsh

local repo="$(ghq list | fzf-tmux --reverse)"
if [[ -n "$repo" ]]; then
  repo="$(ghq list --full-path --exact $repo)"
  BUFFER="cd ${repo}"
  zle accept-line
fi

zle clear-screen
