#!/bin/zsh

readonly IMGCAT_SRC="https://www.iterm2.com/utilities/imgcat"
readonly IMGCAT_DST="$HOME/.local/bin/$(basename "$0")"

if [[ ! -x "$IMGCAT_DST" ]]; then
  curl -sS -o "$IMGCAT_DST" "$IMGCAT_SRC"
  chmod 755 "$IMGCAT_DST"
fi

unset -f imgcat

eval "$IMGCAT_DST" "$@"
