""" Edit
filetype plugin indent on
set encoding=utf-8
set fileencodings=utf-8,euc-jp,sjis,cp932,iso-2022-jp
set fileformats=unix,dos,mac
set backspace=indent,eol,start
set expandtab
set smarttab
set shiftwidth=2
set softtabstop=2
set autoindent
packadd! matchit

""" UI
syntax enable
set display=lastline
set laststatus=2
set lazyredraw
set mouse=a
set number
set showcmd
set showmatch
set ruler
set wildmenu
if $TERM =~ ".*-256color"
  packadd! molokai
  colorscheme molokai
endif

""" Search
set hlsearch
set incsearch
set ignorecase
set smartcase
set wrapscan

""" Files
set viminfo+=n~/.cache/vim/viminfo
set directory=~/.cache/vim/swap
set backup
set backupdir=~/.cache/vim/backup
set undofile
set undodir=~/.cache/vim/undo
for s:d in [&directory, &backupdir, &undodir]
  if !isdirectory(s:d)
    call mkdir(iconv(s:d, &encoding, &termencoding), 'p')
  endif
endfor

""" Key mappings
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>
